### ISSUE TITLE
Critical uncaught error 

### ISSUE THREAD

**Issue by PrzemekLavel** [PayU-EMEA/plugin_woocommerce#19]
Hello,

I accidentaly run into Woocommerce's Logs, and found out that there is a problem with this plugin.

I have everything up to date by the day 20.05.2019r. 

Here is what I found in logs, can you please try to find the problem? 

> 2019-05-16T21:48:19+00:00 CRITICAL Uncaught Error: Call to a member function get_status() on boolean in /public_html/wp-content/plugins/plugin_woocommerce-master/includes/class-woocommerce-payu.php:192
> 
> Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(286): WC_Gateway_PayU->gateway_ipn('')
#1 /public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(113): do_action('woocommerce_api...')
#4 /public_html/wp-includes/class-wp-hook.php(286): WC_API->handle_api_requests(Object(WP))
#5 /public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /public_html/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#7 /public_html/wp-includes/class-wp.php(387): do_action_ref_array('parse_request', Array)
#8 /publi w /public_html/wp-content/plugins/plugin_woocommerce-master/includes/class-woocommerce-payu.php w linii 192

**Comment by PrzemekLavel** [comment]
Anybody?

**Comment by uhlhosting** [comment]
I got the same issue and this breaks also Woocommerce and Guttenberg, any solution?

**Comment by uhlhosting** [comment]
@PrzemekLavel you could try this temporary fix until the developer will get back to this. He is on holidays now from my knowledge.

Hi again,

The issue is in the PayU plugin. The mentioned line from debug.log "103" should not run in the admin, but as the WC dashboard used the REST API it runs anyway.

To fix this we can share with you a workaround. Please replace on plugins\woo-payu-payment-gateway\includes\class-woocommerce-payu.php Line 93:


`if (!(is_admin())) {`
with 
`if (!(is_admin() || wp_is_json_request())) {`

**Comment by uhlhosting** [comment]
Please note the above solution, is just a simple quick workaround to allow me to see the WooCommerce dashboard.

**Comment by Kadigan** [comment]
I'm seeing the same problem, and I believe the issue is due to the order not existing - the `wc_get_order()` function _can also return a boolean_, and this is never verified in the plugin code: te plugin doesn't check if the result is an object or not, and proceeds to attempt to call a method on the result.

One of reliable ways to replicate the error is to block PayU from processing the payment (or otherwise prevent success), and then delete the order in WooCommerce. PayU's servers will periodically attempt to update the order, and since the order is already deleted - `wc_get_order()` should return `false` (instead of the object), triggering the problem.

I would propose a fix (check if the result is an object, emit a proper error code if it's not), but I have no clue what the proper response should be in this case.
