### ISSUE TITLE
Add filter for order statuses

### ISSUE THREAD

**Issue by vaclavgreif** [PayU-EMEA/plugin_woocommerce#42]
Any chance to merge this one https://github.com/PayU-EMEA/plugin_woocommerce/pull/40 please? It's non-breaking change that would allow us to control the status changes.

Thanks!

**Comment by regdos** [comment]
We added filter but only for CANCELED notification because:
* REJECTED has been remover (Payu doesn't send it anymore)
* WAITING_FOR_CONFIRMATION not final status in PayU. WC order status must be set to `payu-waiting` for proper future status changes. 

https://github.com/PayU-EMEA/plugin_woocommerce/commit/86a0bd52c1fa73d908b21110891ac39a1ef44164

**Comment by vaclavgreif** [comment]
Awesome, thanks!
